config/routes.rb
Rails.application.routes.draw do

  
  devise_for :crews, :controllers =>  { :omniauth_callbacks => "crews/omniauth_callbacks" }

  

  resources :articles do
    resources :comments
  end
  

  root 'home#index'  

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :crew
	has_many :comments, dependent: :destroy
	#validates :title, 	presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :crew
  
end

app/models/crew.rb
class Crew < ActiveRecord::Base
  has_many :articles
  has_many :comments

  # Include default devise modules. 
  devise  :database_authenticatable,
          #:confirmable,
          #:recoverable,  
          #:registerable,
          #:rememberable, 
          :trackable, 
          #:timeoutable,
          #:validatable,
          #:lockable,

          :omniauthable, :omniauth_providers => [:facebook]

          
  #def self.koala(auth)
    #access_token = auth['token']
    #facebook = Koala::Facebook::API.new(access_token)
    #facebook.get_object("me?fields=email,name,picture")
  #end

  def self.find_info_from_omniauth_facebook(auth) #find record then update or create from omniauth_facebook
    if the_crew = Crew.where({:provider => auth.provider, :uid => auth.uid,}).first
      Crew.update( #.update is an ActiveRecord::Relation method, requires .update(id, attributes)
        the_crew[:id],
        { :email => auth.info.email, 
          :name => auth.info.name, 
          :image => auth.info.image
        }
      )
      return the_crew
    else # Create a user with a stub password. 
      Crew.create(
        { :provider => auth.provider,
          :uid => auth.uid,
          :email => auth.info.email, 
          :name => auth.info.name, 
          :image => auth.info.image,
          :password => Devise.friendly_token[0,20]
        }
      )
    end
  end

  #def self.find_record_from_omniauth_facebook(auth) #find record or create from omniauth_facebook
    #where({:provider => auth.provider, :uid => auth.uid}).first_or_create do |create_crew| #first_or_create is a ActiveRecord::relative method
      #create_crew.email = auth.info.email
      #create_crew.password = Devise.friendly_token[0,20]
      #create_crew.name = auth.info.name   
      #create_crew.image = auth.info.image 
    #end
  #end

  #def self.new_with_session(params, session)    
    #super.tap do |crew_info|
      #if crew_info = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        #crew_info.email = crew_info["email"] if crew.email.blank?
      #end
    #end

    #super.tap do |crew_info|
      #if hash_from_facebook = session["devise.facebook_data"]
        #crew_info.email = hash_from_facebook.info.email
        #crew_info.name = hash_from_facebook.info.name
        #crew_info.image = hash_from_facebook.info.image
      #end
    #end
  
  #end

  #But when is this method used? 
  #It's used by Devise when something goes wrong when creating your user. 
  #Imagine that the authentication provider doesn't give you an email
  #Well, you can redirect the user to your sign up page where he can complete the signup process. 
  #But if you redirect the user, you lose the data received by the oauth. 
  #The solution is to put this data into the session.
  #So in controller
  ##session["devise.facebook_data"] = env["omniauth.auth"]


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception 
  before_action :authenticate_crew!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	#http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

	def index
    @all_articles = Article.all
  end

	def show
    @article = Article.find(params[:id])
  end

	def new
		@article = Article.new
	end 

	def create
		#render plain: params[:article].inspect
		#@article = Article.new(params[:article])
		@article = Article.new(article_params)

		if @article.save
		  redirect_to article_path(@article)
		else
		  render 'articles/new'
		end
	end 

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to article_path(@article)
		else
			render 'articles/edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		 
		redirect_to articles_path
	end

	#private vars
	private
	  def article_params
	    params.require(:article).permit(:title, :text, :selected_date)
	  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
  	@comment = @article.comments.find(params[:id])
  	@comment.destroy
  	redirect_to article_path(@article)
	end
		
	#private vars
	private
	  def comment_params
	    params.require(:comment).permit(:content)
	  end

end

app/controllers/crews/omniauth_callbacks_controller.rb
class Crews::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook # The name of the method should match the name of the provider.
      
    # Hash content in request.env['omniauth.auth'] refer to evernote "omniauth_facebook" or by the code:
    ##render :text => "<pre>" + env["omniauth.auth"].to_yaml and return

      # Check if no email get from facebook    
    if request.env["omniauth.auth"].info.email.blank?
        redirect_to "/crews/auth/facebook?auth_type=rerequest&scope=email"
    end

    # Koala approach
    ##@crew = Crew.koala(request.env['omniauth.auth']['credentials'])

    # Omniauth approach
    # You need to implement the method below in your model (e.g. app/models/crew.rb)
    
    @crew = Crew.find_info_from_omniauth_facebook(request.env['omniauth.auth'])

      if @crew.persisted? # persisted? is a ActiveRecord::persistence method      
        ##render :text => "<pre>" + @crew_info.to_yaml and return
        ##render :text => "<pre>" + @crew_info[:id].to_s and return
        ##render :text => "<pre>" + @crew_info[:name].to_s and return

        ##sign_in @crew_info
        ##redirect_to root_path(@crew_info)
        sign_in_and_redirect(@crew) #sign_in_and_redirect is a Devise controller helper method
        ##flash[:notice] = "Good"
      else
        ##session['devise.facebook_data'] = request.env['omniauth.auth']  # This is for fast autofilling reg form?
                                                                        # This is for session auto clean up?
        ##redirect_to new_crew_registration_path
        redirect_to new_crew_session_path
      end

    # Simple omniauth approach
    ##@crew_info = Crew.from_omniauth(request.env["omniauth.auth"])
    ##sign_in_and_redirect @crew_info
  
  end # def facebook

end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController

  def index

  end

  def login
    @crew = Crew.koala(request.env['omniauth.auth']['credentials'])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #@articles = Article.all
  	#@hash = Gmaps4rails.build_markers(@articles) do |article, marker|
      #marker.lat article.latitude
      #marker.lng article.longitude

      #marker.infowindow article.content

    #end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_aform.html.erb
<% #form_for :article, url: articles_path do |f| %>
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> 
        prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.date_select :selected_date, :order => [:day, :month, :year] %>  
  </p>
 
  <p>
    <%= f.text_area :content %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/_form.html.erb
<% #form_for :article, url: articles_path do |f| %>
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> 
        prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= render 'form' %>
 
<%= link_to 'My Articles', articles_path %>

app/views/articles/index.html.erb
<!-- Head
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :head do %>
<% end %>
<!-- Header
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :header do %>  

  <%= render 'layouts/header' %>

<% end %>
<!-- Twelve Columns
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :twelve do %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @all_articles.each do |a| %>
    <tr>
      <td><%= a.title %></td>
      <td><%= a.content %></td>
      <td><%= link_to 'Show', article_path(a) %></td>
      <td><%= link_to 'Edit', edit_article_path(a) %></td>
      <td><%= link_to 'Destroy', article_path(a),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>  
</table>

<% end %>
<!-- Contents
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :content do %>
<% end %>
<!-- Misc
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :misc do %>

  

<% end %>

app/views/articles/new.html.erb
<!-- Head
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :head do %>

<% end %>
<!-- Header
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :header do %>  

  <%= render 'layouts/header' %>

<% end %>
<!-- Twelve Columns
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :twelve do %>
  
  <section class="section">
    <%= render 'aform' %>  
  </section>

<% end %>
<!-- Contents
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :content do %>
<% end %>
<!-- Misc
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :misc do %>

  

<% end %>

app/views/articles/show.html.erb
<!-- Head
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :head do %>

<% end %>
<!-- Header
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :header do %>  

  <%= render 'layouts/header' %>

<% end %>
<!-- Twelve Columns
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :twelve do %>

  <!-- Show articles -->
  <p>
    <strong>Title:</strong>
    <%= @article.title %>
  </p>
   
  <p>
    <strong>Text:</strong>
    <%= @article.content %>
  </p>

  <!-- Show comments -->
  <h2>Comments</h2>
  <%= render 'comments/comment' %>

  <!-- Edit comments -->
  <h2>Add a comment</h2>
  <%= render 'comments/cform' %>

  <%= link_to 'Edit', edit_article_path(@article) %>
  <%= link_to 'New Article', new_article_path %>

<% end %>
<!-- Contents
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :content do %>
<% end %>
<!-- Misc
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :misc do %>

  

<% end %>

app/views/comments/_cform.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/_comment.html.erb
<!-- Show comments -->

<% @article.comments.each do |c| %>
	<p>
		<%= c.content %>
	
  		<%= link_to 'Delete', article_comment_path(@article, c),
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
	</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/home/index.html.erb
<!-- Head
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :head do %>

  <style type="text/css">
    body { overflow: hidden; }
  </style>

<% end %>
<!-- Header
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :header do %>  

  <%= render 'layouts/header' %>

<% end %>
<!-- Twelve Columns
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :twelve do %>

  <div id="map"><!-- Google maps lays here --></div>

<% end %>
<!-- Contents
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :content do %>
<% end %>
<!-- Misc
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<% content_for :misc do %>

  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


  <!-- Googlemaps init -->
  <script type="text/javascript">

    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers([
        {
          "lat": 25.079612,
          "lng": 121.234227,
          "picture": {
            "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
            "width":  36,
            "height": 36
          },
          "infowindow": "hello!"
        }
      ]);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });

  </script>


  
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar-spacer"></div> <!-- navbar-spacer -->
<nav id="home-nav", class="navbar">
  <div class="container">

    <div class="pure-menu pure-menu-horizontal">

      <ul class="pure-menu-list pull-left">                  
        <li class="pure-menu-item"><%= image_tag(current_crew[:image], class: 'img-circle') %></li>          
        <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">            
          
          <a href="#" id="crew-name" class="pure-menu-link"><%= current_crew[:name] %></a>
          <ul class="pure-menu-children">            
            <li class="pure-menu-item">
              <%= link_to 'Home', root_path, class: 'pure-menu-link' %>
            </li>
            <li class="pure-menu-item">
              <%= link_to 'My Articles', articles_path, class: 'pure-menu-link' %>
            </li>                    
          </ul> <!-- pure-menu-children -->

        </li> <!-- pure-menu-item pure-menu-has-children pure-menu-allow-hover -->
      </ul> <!-- pure-menu-list pull-left -->
      
      <ul class="pure-menu-list pull-right">
        
        <li class="pure-menu-item">
          <% if crew_signed_in? == true %>
            <%= image_tag('orange-dot.png', class: 'img-dots') %>
          <% else %>
            <%= image_tag('red-dot.png', class: 'img-dots') %>
          <% end %>
        </li>
        <li class="pure-menu-item">
          <%= link_to "Sign out", destroy_crew_session_path, method: :delete, class: 'pure-menu-link' %>
        </li>

      </ul> <!-- pure-menu-list pull-right -->
      
      
    </div> <!-- pure-menu pure-menu-horizontal -->


  </div> <!-- container -->  
</nav> <!-- navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- Moblie Specific Metas -->
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Fonts
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='//fonts.googleapis.com/css?family=Raleway:400,300,600' rel='stylesheet' type='text/css'>

    <!-- Assests
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Title
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <%= favicon_link_tag 'favicon.ico' %>
    <title>Liberta!</title>
    <meta name="description" content="Travel DB">
    <meta name="author" content="Jim uplaabura">

    <!-- Yield head
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <%= yield :head %>

  </head>
  <body>

<!-- Header
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <%= yield :header %>


<!-- Twelve columns
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <div class="container">
      <div class="row">
        <div class="twelve columns">

          <%= yield :twelve %>              

        </div> <!-- twelve columns -->
      </div> <!-- row -->
    </div> <!-- container -->

<!-- Content
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <%= yield :content %>

<!-- Misc
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <%= yield :misc %>

  </body>
</html>